# permissions for end users to edit alertprobes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: alertprobe-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github
    app.kubernetes.io/part-of: github
    app.kubernetes.io/managed-by: kustomize
  name: alertprobe-editor-role
rules:
- apiGroups:
  - probe.rextein.com
  resources:
  - alertprobes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - probe.rextein.com
  resources:
  - alertprobes/status
  verbs:
  - get
