---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - probe.rextein.com
  resources:
  - alertprobes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - probe.rextein.com
  resources:
  - alertprobes/finalizers
  verbs:
  - update
- apiGroups:
  - probe.rextein.com
  resources:
  - alertprobes/status
  verbs:
  - get
  - patch
  - update
